spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:geo
  h2:
    console:
       enabled: true
       settings:
        web-allow-others: true
server.port: 8080





